version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build: ./backend
    environment:
      DB_HOST: ${BACKEND_DB_HOST}
      DB_USER: ${BACKEND_DB_USER}
      DB_PASS: ${BACKEND_DB_PASS}
      DB_NAME: ${BACKEND_DB_NAME}
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app-net

volumes:
  db-data:

networks:
  app-net:
    driver: bridge
